apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: jitsi
  labels:
    k8s-app: jicofo
  name: jicofo
spec:
  template:
    spec:
      # avoid that pods of different shards share zone
      nodeSelector:
        topology.kubernetes.io/zone: ZONE_1
      containers:
        - name: jicofo
          env:
            - name: XMPP_SERVER
              value: shard-0-prosody
