apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- metrics-server.yaml
- grafana-ingress.yaml
- grafana-pvc.yaml
- jvb-pod-monitor.yaml
- prometheus-roleBindingSpecificNamespaces.yaml
- prometheus-roleSpecificNamespaces.yaml
- jitsi-dashboard-configmap.yaml
- bbb-service.yaml
- bbb-service-monitor.yaml

patchesStrategicMerge:
- metrics-server-patch.yaml
