bases: 
- ../../base
resources:
  - certificate.yaml
patchesStrategicMerge:
  - jvb-statefulset-patch.yaml
  - jitsi-ingress-patch.yaml
  - grafana-deployment-patch.yaml
commonLabels:
  env: production
