apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- jitsi-namespace.yaml
- jitsi-secret.yaml
- web-deployment.yaml
- jicofo-deployment.yaml
- prosody-deployment.yaml
- web-configmap.yaml
- prosody-service.yaml
- web-service.yaml
- jitsi-ingress.yaml
- jvb/
