apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/coreos/kube-prometheus?ref=release-0.5
- monitoring/
- https://github.com/GoogleCloudPlatform/metacontroller?ref=v0.4.0
- metacontroller/
- cert-manager/
- ingress-nginx/
- jitsi/

patchesStrategicMerge:
- monitoring/grafana-deployment-patch.yaml
- monitoring/prometheus-adapter-config-map-patch.yaml
