apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: haproxy-ingress
  namespace: jitsi
spec:
  tls:
  - hosts:
    # fill in host here
    - jitsi.domainname
    secretName: jitsi-messenger-schule-tls
